version: '3.8'

services:
  workspace:
    container_name: workspace_azula
    build:
      context: .
      dockerfile: Dockerfile.workspace
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app
    ports:
      - "3000:3000"
    env_file:
      - .env
networks:
  default:
    external:
      name: dev_net
